import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import React, {useState} from "react";
import {useRouter} from "next/navigation"
import {useSession} from "next-auth/react"
import { signOut } from 'next-auth/react';


type TestData = {
  id :   string;
  testString : string; 
  createdAt : string; 
  updatedAt: string;
}

const Home: NextPage = () => {
  const router = useRouter();
  const {data: session} = useSession();
  // console.log(session);

  // const [input, setInput] = useState<string>("");
  // const [data, setData] = useState<TestData>();

  // const {data: testData, isLoading} = api.test.getAll.useQuery<TestData, TestData[]>();

  // const inputHandler = (e:React.FormEvent<HTMLInputElement>) => {
  //   setInput(e.currentTarget.value);
  // }

  // const {mutate} = api.test.update.useMutation({
  //   onSuccess: (res) => {
  //     console.log(res);
  //   }
  // });

  // const buttonClickHandler = () => {}
  //   mutate({input});
  // }
    if(session) {

      return (
        <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>T3 APP test</h1>
        <button onClick={() => signOut({ callbackUrl: 'http://localhost:3000' })}>logout</button>
      </main>
    </>
    );
  }

  return (
    <>
  <Head>
    <title>Create T3 App</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main>
    <h1>T3 APP test</h1>
    <button onClick={()=> router.push('/signin')}>go to the login page</button>
  </main>
  </>
);
};

export default Home;