import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import React, {useState} from "react";

type TestData = {
  id :   string;
  testString : string; 
  createdAt : string; 
  updatedAt: string;
}

const Home: NextPage = () => {

  const [input, setInput] = useState<string>("");
  const [data, setData] = useState<TestData>();

  const {data: testData, isLoading} = api.test.getAll.useQuery<TestData, TestData[]>();

  const inputHandler = (e:React.FormEvent<HTMLInputElement>) => {
    setInput(e.currentTarget.value);
  }

  const {mutate} = api.test.update.useMutation({
    onSuccess: (res) => {
      console.log(res);
    }
  });

  const buttonClickHandler = () => {
    mutate({input});
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>T3 APP test</h1>
        <div className="flex flex-col w-64">
          <input value={input} onChange={inputHandler} placeholder="type in something"></input>
          <button onClick={buttonClickHandler}>click to add string to the list</button>
        </div>
        <div>
          {
            testData?.length ?
            testData.map((data) => {
              return <h1 key={data.id as React.Key}>{data.testString}</h1>
            })
            : "loading...."
          }
        </div>
      </main>
    </>
  );
};

export default Home;